---
title: "Exploratory Analysis of Remote Work by Class of Worker: 2018-2023"
author: "Justine Shakespeare"
description: "This exploratory analysis examines trends in working from home in the United States between 2018 and 2023 using Census data from the American Community Survey table B08528 (Means of Transportation to Work by Class of Worker for Workplace Geography). It highlights national and state-level changes in work-from-home rates, and compares remote work patterns by class of worker before and after the COVID-19 pandemic. The analysis also identifies which worker groups most quickly returned to in-person work by 2023 and explores potential correlations between remote work prevalence and state-level political alignment based on the 2020 presidential election."
date: "07/23/2025"
format:
  html:
    df-print: paged
    toc: true
    code-fold: true
    code-copy: true
    code-tools: true
editor_options: 
  chunk_output_type: console
---

```{r}
#| label: setup
#| warning: false
#| message: false

library(tidyverse)
library(knitr)

knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```

# Research Questions:

1. What is the national trend of work from home from 2018 to 2023?
2. Which states saw the largest increases or decreases in remote work over this period? with regards to both absolute and percentage change.
3. Which class of workers worked from home the most before Covid-19 pandemic? Which worked from home the most after the pandemic?
4. Which class of workers was the quickest to return to the office (and so decrease work from home) after the pandemic began to subside (2023)?
5. Taking precautions during the Covid-19 pandemic, including working from home, became very politicized. Does the state-level data on work from home correlate with electoral politics and specific which states voted for Biden vs. Trump in 2020?



Exploratory Analysis of Remote Work by Class of Worker Using American Community Survey B08528 Workplace Geography Data







Data source:

U.S. Census Bureau, U.S. Department of Commerce. (n.d.). Means of Transportation to Work by Class of Worker for Workplace Geography. American Community Survey, ACS 1-Year Estimates Detailed Tables, Table B08528. Retrieved July 23, 2025, from https://data.census.gov/table/ACSDT1Y2023.B08528?t=Class+of+Worker&d=ACS+1-Year+Estimates+Detailed+Tables.
